// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPDD9m7Q78dzcuRXKr5t5k0ZIkuFm-oDs',
    appId: '1:993829837282:web:f3562699fd6172c019c1bb',
    messagingSenderId: '993829837282',
    projectId: 'productivityapp-c8192',
    authDomain: 'productivityapp-c8192.firebaseapp.com',
    storageBucket: 'productivityapp-c8192.firebasestorage.app',
    measurementId: 'G-QFDBHNSFS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDel0zQ2MB3ElXP0_UnoGg9DLmtC_pUURg',
    appId: '1:993829837282:android:5b3c06b451fb8c2f19c1bb',
    messagingSenderId: '993829837282',
    projectId: 'productivityapp-c8192',
    storageBucket: 'productivityapp-c8192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvRJjkgM54CtJ6v-v7ltlJINCciFlPdwk',
    appId: '1:993829837282:ios:fef5e95891710ec519c1bb',
    messagingSenderId: '993829837282',
    projectId: 'productivityapp-c8192',
    storageBucket: 'productivityapp-c8192.firebasestorage.app',
    iosBundleId: 'com.example.productivityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvRJjkgM54CtJ6v-v7ltlJINCciFlPdwk',
    appId: '1:993829837282:ios:fef5e95891710ec519c1bb',
    messagingSenderId: '993829837282',
    projectId: 'productivityapp-c8192',
    storageBucket: 'productivityapp-c8192.firebasestorage.app',
    iosBundleId: 'com.example.productivityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPDD9m7Q78dzcuRXKr5t5k0ZIkuFm-oDs',
    appId: '1:993829837282:web:52bedd1174d494d819c1bb',
    messagingSenderId: '993829837282',
    projectId: 'productivityapp-c8192',
    authDomain: 'productivityapp-c8192.firebaseapp.com',
    storageBucket: 'productivityapp-c8192.firebasestorage.app',
    measurementId: 'G-CYT40E7QHW',
  );

}